name: turbohopp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=openblas
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - expat=2.6.2=h59595ed_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.12.1=h267a509_2
  - icu=73.2=h59595ed_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=22_linux64_openblas
  - libcblas=3.9.0=22_linux64_openblas
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_7
  - libgfortran5=13.2.0=hca663fb_7
  - libglib=2.80.2=hf974151_0
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=22_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libuuid=2.38.1=h0b41bf4_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4.20240210=h59595ed_0
  - numpy=1.26.4=py310hb13e2d6_0
  - ocl-icd=2.3.2=hd590300_1
  - ocl-icd-system=1.0.0=1
  - openbabel=3.1.1=py310hbff9852_9
  - openmm=8.1.1=py310h43b6314_1
  - openssl=3.3.1=hb9d3cd8_3
  - pcre2=10.43=hcad00b1_0
  - pdbfixer=1.9=pyh1a96a4e_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.10.8=h4a9ceb5_0_cpython
  - python_abi=3.10=4_cp310
  - readline=8.2=h8228510_1
  - scipy=1.15.2=py310h210a465_1
  - setuptools=69.2.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - biopandas==0.5.1
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - exceptiongroup==1.3.1
      - filelock==3.20.3
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - gemmi==0.7.4
      - gitdb==4.0.12
      - gitpython==3.1.46
      - idna==3.11
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - lightning-utilities==0.15.2
      - looseversion==1.1.2
      - markupsafe==3.0.3
      - meeko==0.7.1
      - mmtf-python==1.1.3
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rdkit==2025.9.3
      - requests==2.32.5
      - sentry-sdk==2.49.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - tomli==2.4.0
      - torch==2.9.1
      - torch-geometric==2.7.0
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tqdm==4.67.1
      - triton==3.5.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - vina==1.2.7
      - wandb==0.24.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/mrcong/miniconda3/envs/turbohopp
